title: P2PU & Suomen eOppimiskeskus ry
description: 'Opintopiirit saapuvat Suomeen!

  Tervetuloa opiskelemaan opintopiiriin (Learning Circle) yhdessä muiden samasta asiasta
  kiinnostuneiden kanssa - verkossa ja kasvokkain! Opintopiiri kokoontuu yhteisesti
  sovitun aikataulun mukaan (noin kerran viikossa muutaman viikon ajan). Opiskelu
  on maksutonta.'
language: fi
partner_url: https://eoppimiskeskus.fi/
